name: CI - Build and Push docker images
on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                  
            - name: Build and Push Backend Image
              uses: docker/build-push-action@v5
              with:
                context: ./backend
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/student-feedback-backend:latest

            - name: Build and Push Frontend Image
              uses: docker/build-push-action@v5
              with:
                context: ./frontend
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/student-feedback-frontend:latest